### ISSUE TITLE
Difference in site vs extension

### ISSUE THREAD

**Issue by benjick** [dumfan/apk-chrome#1]
_Kopparbergs Special Brew 10%_ is at an APK of **2.51** according to the site. The chrome extention reports it being **2.65** (http://www.systembolaget.se/dryck/ol/kopparbergs-1131512)

However, _Jeanneret Shiraz Grenache Rosé_ is reporting the same APK using both methods (http://www.systembolaget.se/dryck/roseviner/jeanneret-645501)

**Comment by esprimo** [comment]
Because the price is different. On systembolaget.se it's 18.90 kr and on apk.kother.io it's 19.90 kr. Either the data we use on apk.kother.io is old or systembolaget delivers erroneus data.  Probably the later.

**Comment by benjick** [comment]
Good catch, I wonder why. I'll cross-check the xml and report it to
systembolaget

**Comment by benjick** [comment]
https://twitter.com/benjick/status/615637006081753088

**Comment by devvis** [comment]
:dancer:
